'use client'
import { useState } from 'react'
import type { Metadata } from 'next'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const [value, setValue] = useState('')
  return (
    <html lang='en'>
      <head>
        <link rel='icon' type='image/svg+xml' href='/trello.svg' />
      </head>
      <body className={`${inter.className}`}>
        <div className='flex flex-col min-h-screen'>
          <Header searchValue={value} onSearchValue={setValue} />
          <div className='pt-20 flex-1'>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
